//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationUserMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogInsert
    {
        public int BlogId { get; set; }
        public string BlogHeading { get; set; }
        public string ExperienceSharing { get; set; }
        public string Motivation { get; set; }
        public string Advice { get; set; }
    }
}
