//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationUserMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Doctor
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string BMARegistrationNo { get; set; }
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Age { get; set; }
        public string ExperienceYear { get; set; }
        public string AreaofSpeciality { get; set; }
        public string Residence { get; set; }
    }
}
