//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationUserMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int PrescriptionId { get; set; }
        public string FullName { get; set; }
        public int Age { get; set; }
        public int Weight { get; set; }
        public string Date { get; set; }
        public string DiagnosedWith { get; set; }
        public string BloodPressure { get; set; }
        public string HeartRate { get; set; }
        public string DragName { get; set; }
        public string Unit { get; set; }
        public string Dosage { get; set; }
        public string Examination { get; set; }
        public string ThingsToFollow { get; set; }
        public string Signature { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
