//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationUserMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remedy
    {
        public int Id { get; set; }
        public string RemedyHeading { get; set; }
        public string Remedysymptom { get; set; }
        public string Remedydescription { get; set; }
        public string Remedymedicine { get; set; }
    }
}
